name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Debug

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
          
      - id: version-retriver
        run: |
          "SHORT_SHA=$("${{ github.sha }}".SubString(0, 8))" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Build Artifacts
        uses: ./.github/actions/build-artifacts
        with:
          sln-path: ${{ env.SOLUTION_FILE_PATH }}
          build-config: ${{ env.BUILD_CONFIGURATION }}
          version-tag: ${{ github.ref_name }}-${{ steps.version-retriver.outputs.SHORT_SHA }}
