name: Release

on:
  push:
    tags:
      - 'v**'

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Build Artifacts
        uses: ./.github/actions/build-artifacts
        with:
          sln-path: ${{ env.SOLUTION_FILE_PATH }}
          build-config: ${{ env.BUILD_CONFIGURATION }}
          version-tag: ${{ github.ref_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: 'artifacts'
          path: 'output'
      - run: ls -R output

      - name: Publish release
        uses: softprops/action-gh-release@v3
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          make_latest: true
          preserve_order: true
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          files: |
            output/**/*.@(dll|pdb)
